name: Accessibility-alt-text-bot

on:

issues:

types: [opened, edited]

pull_request:

types: [opened, edited]

issue_comment:

types: [created, edited]

discussion:

types: [created, edited]

discussion_comment:

types: [created, edited]


permissions:

issues: write

pull-requests: write

discussions: write


jobs: accessibility_alt_text_bot:

name: Check alt text is set
